name: test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - name: set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.1"
      - name: flutter pub get
        run: flutter pub get
      - name: flutter build
        run: flutter build appbundle --debug
  ios:
    runs-on: macos-latest
      steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.1"
      - name: flutter pub get
        run: flutter pub get
      - name: flutter build
        run: flutter build ios --debug --no-codesign
