name: test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  test:
    name: flutter test
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: set up flutter
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.10.1"
      - name: flutter pub get
        run: flutter pub get
      - name: flutter widget test
        run: flutter test test/widget_test.dart
      - name: flutter unit test
        run: flutter test test/unit_test.dart
